---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/dorparas/blog/
    - /bin/cp -R server $DEPLOYPATH
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm install
