name: CPanel Deploy Workflow
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: pinkasey/cpanel-deploy-action@v1.1.2
        with:
          hostname: "https://dorparasti.xyz"
          repository_root: "/home2/dorparas/repositories/Benvis"
          branch: master
          cpanel_token: "${{ secrets.CPANEL_TOKEN }}"
          cpanel_username: "dorparas"
